/*
 * Copyright 2026 Rawvoid(https://github.com/rawvoid)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.github.rawvoid.jaxb.plugin;

import com.sun.codemodel.*;
import com.sun.tools.xjc.Options;
import com.sun.tools.xjc.outline.Outline;
import org.xml.sax.ErrorHandler;
import org.xml.sax.SAXException;

import java.util.*;

/**
 * JAXB plugin that flattens inner classes generated by XJC.
 *
 * @author Rawvoid
 */
@Option(name = "Xflatten-inner-class", description = "Flatten inner classes generated by XJC")
public class FlattenInnerClassPlugin extends AbstractPlugin {

    @Override
    public boolean run(Outline outline, Options opt, ErrorHandler errorHandler) throws SAXException {
        var classes = outline.getClasses().stream()
            .sorted(Comparator.comparing(c -> c.implClass.fullName()))
            .toList();

        Set<JClassContainer> processedContainers = new HashSet<>();
        classes.forEach(classOutline -> {
            var implClass = classOutline.implClass;

            var parentContainer = implClass.parentContainer();
            if (processedContainers.contains(parentContainer)) {
                return;
            }
            processedContainers.add(parentContainer);

            var directClasses = getClasses(parentContainer);
            flattenClasses(parentContainer, directClasses);
        });

        // outline.getAllPackageContexts().forEach(packageOutline -> {
        //     var classes = packageOutline.getClasses().stream()
        //         .map(classOutline -> classOutline.implClass)
        //         .collect(Collectors.groupingBy(c -> c.name().toUpperCase()));
        //
        //     var jPackage = packageOutline._package();
        //     flattenClasses(jPackage, classes);
        // });
        //
        // outline.getClasses().forEach(classOutline -> {
        //     var implClass = classOutline.implClass;
        //
        //     var innerClasses = getInnerClasses(implClass);
        //     flattenClasses(implClass, innerClasses);
        // });
        return true;
    }

    private Map<String, List<JDefinedClass>> getClasses(JClassContainer container) {
        Map<String, List<JDefinedClass>> classes = new TreeMap<>();
        var queue = new LinkedList<JClassContainer>();
        queue.offer(container);
        while (!queue.isEmpty()) {
            var currentContainer = queue.poll();
            var iterator = currentContainer.classes();

            while (iterator.hasNext()) {
                var definedClass = iterator.next();
                queue.offer(definedClass);

                classes.computeIfAbsent(definedClass.name(), k -> new ArrayList<>())
                    .add(definedClass);
            }
        }

        return classes;
    }

    private void flattenClasses(JClassContainer container, Map<String, List<JDefinedClass>> classes) {
        if (classes == null || classes.isEmpty()) {
            return;
        }

        classes.forEach((name, classList) -> {
            if (classList.size() == 1) {
                var definedClass = classList.getFirst();
                if (isPublic(definedClass)
                    && definedClass.parentContainer() instanceof JDefinedClass
                    && definedClass.parentContainer() != container
                    && isMoveSafety(container, definedClass.name())) {
                    moveClass(definedClass, container);
                }
            }
        });
    }

    private boolean isMoveSafety(JClassContainer container, String className) {
        var upperCaseClassName = className.toUpperCase();
        var iterator = container.classes();
        while (iterator.hasNext()) {
            var definedClass = iterator.next();
            if (definedClass.name().toUpperCase().equals(upperCaseClassName)) {
                return false;
            }
        }
        return true;
    }

    private void moveClass(JDefinedClass definedClass, JClassContainer newContainer) {
        removeFromParentContainer(definedClass);
        setParentContainer(definedClass, newContainer);
        addClassToContainer(definedClass, newContainer);
        if (newContainer.isPackage()) {
            clearStaticModifier(definedClass.mods());
        }
    }

    private void removeFromParentContainer(JDefinedClass definedClass) {
        var parentContainer = definedClass.parentContainer();

        if (parentContainer instanceof JPackage jPackage) {
            jPackage.remove(definedClass);
        } else {
            var classes = getContainerClassesMap(parentContainer);
            classes.values().removeIf(i -> i == definedClass);
        }
    }

    private void addClassToContainer(JDefinedClass definedClass, JClassContainer container) {
        var classes = getContainerClassesMap(container);
        var className = container instanceof JPackage
            ? definedClass.name()
            : definedClass.name().toUpperCase();
        classes.put(className, definedClass);
    }

    private void setParentContainer(JDefinedClass definedClass, JClassContainer newContainer) {
        try {
            var outerField = JDefinedClass.class.getDeclaredField("outer");
            outerField.setAccessible(true);
            outerField.set(definedClass, newContainer);
        } catch (NoSuchFieldException | IllegalAccessException ex) {
            throw new IllegalStateException("Failed to update class container for " + definedClass.fullName(), ex);
        }
    }

    private Map<String, JDefinedClass> getContainerClassesMap(JClassContainer container) {
        try {
            var field = container instanceof JPackage
                ? JPackage.class.getDeclaredField("classes")
                : JDefinedClass.class.getDeclaredField("classes");
            field.setAccessible(true);
            @SuppressWarnings("unchecked")
            var classes = (Map<String, JDefinedClass>) field.get(container);
            if (classes == null) {
                classes = new TreeMap<>();
                field.set(container, classes);
            }
            return classes;
        } catch (NoSuchFieldException | IllegalAccessException ex) {
            throw new IllegalStateException("Failed to access class container map", ex);
        }
    }

    private boolean isPublic(JDefinedClass definedClass) {
        var mods = definedClass.mods().getValue();
        return (mods & JMod.PUBLIC) != 0;
    }

    private void clearStaticModifier(JMods mods) {
        try {
            var flagsField = JMods.class.getDeclaredField("mods");
            flagsField.setAccessible(true);
            var flags = (int) flagsField.get(mods);
            flagsField.set(mods, flags & ~JMod.STATIC);
        } catch (NoSuchFieldException | IllegalAccessException ex) {
            throw new IllegalStateException("Failed to clear static modifier", ex);
        }
    }
}
