/*
 * Copyright 2026 Rawvoid(https://github.com/rawvoid)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.github.rawvoid.jaxb.plugin;

import io.github.rawvoid.jaxb.AbstractXJCMojoTestCase;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlElementWrapper;
import jakarta.xml.bind.annotation.XmlType;
import org.junit.jupiter.api.Test;

import java.lang.reflect.Method;
import java.lang.reflect.ParameterizedType;
import java.util.Arrays;
import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;

public class ElementWrapperPluginTest extends AbstractXJCMojoTestCase {

    @Test
    public void testElementWrapper() throws Exception {
        var args = List.<String>of(
            "-Xelement-wrapper"
        );
        var classes = testExecute(args, ".*RootType", (source, clazz) -> {
            var itemsField = clazz.getDeclaredField("items");
            var xmlElementAnno = itemsField.getAnnotation(XmlElement.class);
            var xmlElementWrapper = itemsField.getAnnotation(XmlElementWrapper.class);

            assertThat(xmlElementAnno).isNotNull();
            assertThat(xmlElementAnno.name()).isEqualTo("item");
            assertThat(xmlElementWrapper).isNotNull();
            assertThat(xmlElementWrapper.name()).isEqualTo("##default");
            // targetNamespace is covered by package-info; do not restate it on the field.
            assertThat(xmlElementWrapper.namespace()).isEqualTo("##default");

            // Field is List<String> after model-level flattening.
            assertThat(List.class.isAssignableFrom(itemsField.getType())).isTrue();
            var genericType = itemsField.getGenericType();
            assertThat(genericType).isInstanceOf(ParameterizedType.class);
            var typeArgs = ((ParameterizedType) genericType).getActualTypeArguments();
            assertThat(typeArgs).hasSize(1);
            assertThat(typeArgs[0]).isEqualTo(String.class);

            // Collection properties generated by XJC expose a getter, not a setter.
            assertThat(Arrays.stream(clazz.getDeclaredMethods())
                .map(Method::getName)
                .anyMatch(name -> name.equals("getItems"))).isTrue();
            assertThat(Arrays.stream(clazz.getDeclaredMethods())
                .map(Method::getName)
                .noneMatch(name -> name.equals("setItems"))).isTrue();

            // Flattened property must keep its original position (name, items, count).
            var propOrder = clazz.getAnnotation(XmlType.class).propOrder();
            assertThat(propOrder).containsExactly("name", "items", "count");
            var fieldNames = Arrays.stream(clazz.getDeclaredFields())
                .map(f -> f.getName())
                .filter(n -> !n.contains("$"))
                .toList();
            assertThat(fieldNames).containsExactly("name", "items", "count");
        });

        // Wrapper class Items should be removed from the model when remove-wrapper-class=true.
        assertThat(classes.stream().map(Class::getName))
            .noneMatch(name -> name.endsWith(".Items"));
    }

    @Test
    public void testKeepWrapperClass() throws Exception {
        var args = List.of(
            "-Xelement-wrapper",
            "-remove-wrapper-class=false"
        );
        var classes = testExecute(args, ".*RootType", (source, clazz) -> {
            var itemsField = clazz.getDeclaredField("items");
            assertThat(itemsField.getAnnotation(XmlElementWrapper.class)).isNotNull();
            assertThat(itemsField.getAnnotation(XmlElement.class)).isNotNull();
            assertThat(List.class.isAssignableFrom(itemsField.getType())).isTrue();
        });

        assertThat(classes.stream().map(Class::getName))
            .anyMatch(name -> name.endsWith(".Items"));
    }
}
